### ISSUE TITLE
Copying to local memory is more efficient

### ISSUE THREAD

**Issue by jomigo96** [ekspek/sai-2018#7]
https://github.com/ekspek/sai-2018/blob/aa2f5f02ed6d9a30d9c6b9a20de8e96cab75fc0d/project/main.c#L102

**Comment by ekspek** [comment]
~u wot~ Thanks for the input, we'll get around to it

**Comment by ekspek** [comment]
Added in commit e70a603ec82b330ffccd50a26b2eba37bbcbb6f3. Closing issue.
